version: '2'

services:
    user:
        build:
            context: .
#        image: weaveworksdemos/user
        image: 74734589924/front-end:1.0.1
        hostname: front-end
        restart: always
        cap_drop:
            - all
        cap_add:
            - NET_BIND_SERVICE
        read_only: true
        environment:
            - reschedule=on-node-failure
        ports:
            - "8079:8079"
